### ISSUE TITLE
List of our features not included in 0.9.5

### ISSUE THREAD

**Issue by szepeviktor** [szepeviktor/fix-w3tc#116]
Please list our implemented features not in v0.9.5

And maybe 0.9.5 bugs.

Was: #57

**Comment by vijayaraghavanramanan** [comment]
Two Implemented features (incomplete list):

- fixed AMP errors. W3TC loads minified CSS/JS files on AMP pages when minify is set to manual in W3TC. This shouldn't happen and is fixed here. 
- fixed Sitemap priority bug. Yoast SEO has removed the priority column but W3TC assumes a default of 0 and hence doesn't prime pages. It is fixed here.

**Comment by charlesLF** [comment]
@vijayaraghavanramanan : already patched on my branch
https://github.com/charlesLF/fix-w3tc/tree/w3tc-0-9-5

**Comment by marian-kadanka** [comment]
0a69db3093db6d81e09f7d08e5d72b541ffe7e4c get_currentuserinfo() -> wp_get_current_user() isn't fixed in upstream 0.9.5

**Comment by amiga-500** [comment]
Implementations in fix-w3tc that are not in 0.9.5?  It's been a while so i'll have to get back to this another time ... it's late here in Canada so i'm dozing off, but off the top of my head:

- php 7 compatibility is [still a problem for 0.9.5](https://github.com/szepeviktor/fix-w3tc/issues/57#issuecomment-250079609) @ 67 errors / 57 warnings vs fix-w3tc @ 0 errors / 0 warnings.
- The "_Cache Feeds_" option in 0.9.5 (and 0.9.4.1) never caches.  It works in fix-w3tc.  It's because of the mime type.  w3tc official still assumes wordpress' returning header (when caching the page) is "_text/xml_" for all feeds when in fact are "_application/rss, application/rdf_, etc".  And so the "_/feed_" directory (and its cache) which w3tc would normally generate is never done.  After getting this working it was discovered w3tc sends back the wrong mime type too for disk enhanced (always text/html) -- still does the same in 0.9.5 (when looking in code).   fix-w3tc fixes this too so that returned cached feeds can render correctly on the client-side browser instead of being all garbled up.
- New filter added: _w3tc_pgcache_lifetime_  -- allows one to set the cache lifetime on a page-by-page basis (not including Disk Enhanced)
- Cached xml sitemaps also return back the wrong mime type under disk enhanced.
- More support for regex was added in several existing fields for minify and page cache.  
- _Accepted query strings_ and _Rejected cookies_ in 0.9.5 still look at the keys only.  So if someone were to give a key/value pair it would fail.  fix-w3tc expanded this to allow the option to include key/value pairs and regex customizing.
- 0.9.5 still triggers php warnings when u attempt to use a "~" in the few boxes that do allow regex.  It's because no escaping of the delimiter was done (the code uses "~" commonly).
- Four new "_Never Cache Pages..._" textarea  boxes were added to allow exclusions based on category slugs, tag slugs, author login ids, and custom fields.  These boxes can potentially make it easier to exclude large swaths of existing (and future) posts without having to type each uri by hand in the w3tc exclusion box (e.g. if someone has a members category of several posts with new posts always being generated which should never be cached); another example: a post author doesnt want her new post ever cached so she could use the post's custom fields area and add e.g, name=_w3tc_ value = _dontcache_ to never cache her new post (assuming the admin had made such an option available via this page cache option)
- Disk enhanced caching of query strings.  It seems 0.9.5 still cannot cache query strings when using disk enhanced.
- PageSpeed widget now includes a new _Key Restriction (Referrer)_ box.  This gives the user an option to add an extra layer of security (when enabled under Google APIs' credentials area) when accessing their pagespeed data (to help prevent authorized use and quota theft).

Ok i'm getting super tired so i will continue tomorrow or another day.

Cheers
Kimberly

**Comment by lukecav** [comment]
These issues where fixed in the 0.9.5.1 release.

[https://wordpress.org/plugins/w3-total-cache/changelog/](url)

= 0.9.5.1= * Fixed missing namespace, which caused issues with other implementations of Google APIs * Fixed handling Cloudflare zone list being incomplete for users with many zones * Added extension to support Accelerated Mobile Pages (AMP) * Added notification for users that are still using PHP 5.3 (end of life in 2011) * Improved default settings * Improved compatibility with Yoast SEO sitemap caching * Improved compatability with Jetpack * Improved directory handling on IIS * Improved backwards compatibility for 3rd party implementations against legacy W3TC functions

**Comment by vijayaraghavanramanan** [comment]
I am still getting error on AMP pages (js/css minified files inserted in html), even though this changelog says it supports and that there are indeed new files in the release which seem to solve the issue :-(

**Comment by vijayaraghavanramanan** [comment]
Apologies. There's a new extension for AMP support and one has to activate it. Ignore my previous comment.

**Comment by nigrosimone** [comment]
@charlesLF you can clone your branch https://github.com/charlesLF/fix-w3tc/tree/w3tc-0-9-5 here?

**Comment by charlesLF** [comment]
Ok, pushed to a new branch: https://github.com/szepeviktor/fix-w3tc/tree/w3tc-0-9-5

Let's keep v0.9.5 separate from the master branch.
